labelA: parton
labelB: delphes
fnA: ../data/train/QCD_500GeV_parton.json.gz
fnB: ../data/train/QCD_500GeV_delphes.json.gz
optimizer: Adam
learning_rate: 0.0002
opt_beta_1: 0.5
nev: 1000
navg: 20
npixels: 24
epochs: 2
zca: true
batch_size: 1
g_filters: 32
d_filters: 64
lambda_cycle: 10.0
lambda_id_factor: 0.1
